### ISSUE TITLE
add url download, optionally unzip, extract p8 file

### ISSUE THREAD

**Issue by digarok** [digarok/Appy#5]
It would be good to reference remote archives so you could do things like download the ProDOS8 disk and pull off the PRODOS.SYSTEM file.

Possible syntax:
```
remotes:
- url: https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/masters/prodos/ProDOS_2_4_2.dsk
  unzip: false
  p8extract:
  - location: /prodos/prodos.system
    out: ./build
```
